import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import { Toaster } from "sonner";
import { headers } from "next/headers";
import "./globals.css";
import AppKitProvider from "@/context/appkit";
import { Navbar } from "@/components/navbar";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["vietnamese"],
});
export const metadata: Metadata = {
  title: "Orion Trading",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersData = await headers();
  const cookies = headersData.get("cookies");
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.className} antialiased`}>
        <AppKitProvider cookies={cookies}>
          <Navbar />
          {children}
        </AppKitProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
